# Generated by Django 6.0.2 on 2026-02-28 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_sample_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('discription', models.TextField()),
                ('worker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='workers.worker')),
            ],
        ),
    ]
